version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-patch"]
  - dependency-name: "@date-io/date-fns"
    versions:
    - ">= 2.a, < 3"
  - dependency-name: eslint-plugin-react
    versions:
    - "> 7.20.0, < 7.21"
  - dependency-name: eslint-plugin-react-hooks
    versions:
    - "> 4.0.4, < 4.1"
  - dependency-name: i18next
    versions:
    - ">= 19.7.a, < 19.8"
  - dependency-name: i18next
    versions:
    - "> 19.9.0, < 19.10"
  - dependency-name: i18next-browser-languagedetector
    versions:
    - "> 6.0.0, < 6.1"
  - dependency-name: i18next-http-backend
    versions:
    - "> 1.0.15, < 1.1"
  - dependency-name: jsrsasign
    versions:
    - "> 8.0.20, < 8.1"
  - dependency-name: jsrsasign
    versions:
    - "> 9.0.0, < 9.1"
  - dependency-name: react-i18next
    versions:
    - "> 11.7.0, < 11.8"
  - dependency-name: react-redux
    versions:
    - "> 7.2.0, < 7.3"
  - dependency-name: single-spa-react
    versions:
    - "> 3.0.0, < 3.1"
  - dependency-name: typescript
    versions:
    - "> 3.9.6, < 3.10"
  - dependency-name: typescript
    versions:
    - "> 4.2.2, < 4.3"
  - dependency-name: "@types/jest"
    versions:
    - "> 26.0.4, < 26.1"
  - dependency-name: "@types/jsrsasign"
    versions:
    - "> 8.0.3, < 8.1"
  - dependency-name: "@types/node"
    versions:
    - "> 14.0.20, < 14.1"
  - dependency-name: "@types/node"
    versions:
    - "> 14.14.31, < 14.15"
  - dependency-name: "@types/react"
    versions:
    - "> 16.9.41, < 16.10"
  - dependency-name: "@types/react-virtualized"
    versions:
    - "> 9.21.10, < 9.22"
  - dependency-name: "@welldone-software/why-did-you-render"
    versions:
    - "> 4.2.5, < 4.3"
  - dependency-name: i18next-http-backend
    versions:
    - 1.2.1
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: date-fns
    versions:
    - 2.16.1
    - 2.18.0
    - 2.19.0
    - 2.20.2
    - 2.21.0
  - dependency-name: cypress
    versions:
    - 6.6.0
    - 6.7.1
    - 6.8.0
    - 7.0.1
    - 7.1.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: jsrsasign
    versions:
    - 10.1.13
  - dependency-name: "@welldone-software/why-did-you-render"
    versions:
    - 6.0.5
    - 6.1.0
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.29
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.0
    - 4.14.2
    - 4.15.0
  - dependency-name: eslint-config-react-app
    versions:
    - 6.0.0
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.2

# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "00:00"
    timezone: Europe/London